name: ci-golang-workflow

on: [push]

jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22

      - name: Run tests
        run: go test ./...

      - name: Run application
        run: go run math.go

      - name: Make changes
        run: |
          # Adicione aqui o script ou comandos que fazem as mudanças necessárias nos workflows
          echo "Making some changes..."
          # Exemplo: echo "# New workflow" >> .github/workflows/new-workflow.yml

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update workflow"
          git push
